#import "../user/UserFragment.gql"

mutation Singin($loginUserInput: LoginUserInput!) {
  singin(loginUserInput: $loginUserInput) {
    user {
      ...UserParts
    }
    access_token
    reflesh_token
  }
}
