#import "./UserFragment.gql"

mutation UpdateUser($updateUserId: ID!, $updateUserInput: UpdateUserInput!) {
  updateUser(id: $updateUserId, updateUserInput: $updateUserInput) {
    ...UserParts
    createdAt
    updatedAt
  }
}
